# mount 인스턴스 설정: Service Principal 인증
# 파일 위치: /etc/rclone/mounts/azblob-sp.conf
# 서비스: systemctl start rclone-mount@azblob-sp.service

REMOTE=azblob-sp-secret:mycontainer
MOUNTPOINT=/mnt/azureblob-sp
EXTRA_ARGS=--allow-other --vfs-cache-mode writes --vfs-cache-max-size 2G
